import time
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
options = webdriver.ChromeOptions()
options.headless = True
driver = webdriver.Chrome(options=options)
driver.maximize_window()
driver.delete_all_cookies()
driver.get("https://qa.pegdesk.com/")
print("Project title is: ", driver.title)
ex_wait = WebDriverWait(driver, 15)
print("1.Check whether superadmin is able to sign in Successfully with given login ")
driver.find_element_by_name("user[email]").send_keys("dev@bitcot.com")
driver.find_element_by_name("user[password]").send_keys("bitcotadmin")
driver.find_element_by_xpath("(//button)[contains(text(),'Sign In')]").click()
time.sleep(5)
print("Sign In Successfully")
print("2. Check whether superadmin is able to filter the qutoes")
driver.find_element_by_link_text("Reports").click()
print("2.1 Quotes Filter:")
time.sleep(5)
driver.find_element_by_xpath("//li/div/div/div/div").click()
driver.find_element_by_xpath("//div[@id='react-select-2-option-0-0']").click()
time.sleep(5)
driver.find_element_by_xpath("//label/div/div/input").click()
time.sleep(3)
driver.find_element_by_xpath("//span[@id='basic-addon2']/i").click()
time.sleep(3)
driver.find_element_by_xpath("//div[@class='react-datepicker__day react-datepicker__day--001']").click()
time.sleep(3)
driver.find_element_by_xpath("//div[2]/label/div[2]/span/i").click()
time.sleep(3)
driver.find_element_by_xpath("//div[@class='react-datepicker__day react-datepicker__day--015 react-datepicker__day--keyboard-selected react-datepicker__day--today']").click()
time.sleep(3)
driver.find_element_by_xpath("//button[@type='submit']").click()
time.sleep(10)
print("Quotes Filter is shown with full page screenshot")
#Full page screenshot
S = lambda X: driver.execute_script('return document.body.parentNode.scroll'+X)
driver.set_window_size(S('Width'), S('Height'))
driver.find_element_by_tag_name('body').screenshot('rqp.png')
time.sleep(5)