import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
driver = webdriver.Chrome()
driver.maximize_window()
driver.delete_all_cookies()
driver.get("https://staging-node.pegdesk.com/")
print("Project title is: ", driver.title)
ex_wait = WebDriverWait(driver, 15)
print("1.Check whether superadmin is able to sign in Successfully with given login ")
driver.find_element_by_name("user[email]").send_keys("dev@bitcot.com")
driver.find_element_by_name("user[password]").send_keys("bitcotadmin")
sign_in = driver.find_element_by_xpath("(//button)[contains(text(),'Sign In')]").click()
time.sleep(5)
driver.find_element_by_link_text("Users").click()
time.sleep(5)
driver.find_element_by_xpath("//a[@class='btn btn-secondary cst_btn']").click()
time.sleep(5)
driver.find_element_by_name("user[first_name]").send_keys("Test")
driver.find_element_by_xpath("//input[@name='user[last_name]']").send_keys("QA")
role = Select(driver.find_element_by_xpath("//select[@name='user[role]']"))
role.select_by_value("admin")
time.sleep(3)
position = Select(driver.find_element_by_xpath("//select[@name='user[position_id]']")).select_by_visible_text('Testor')
time.sleep(3)
driver.find_element_by_xpath("//input[@name='user[email]']").send_keys("testqa@bitcot.com")
branch = Select(driver.find_element_by_xpath("//select[@name='user[region_id]']")).select_by_visible_text('All')
time.sleep(3)
driver.find_element_by_xpath("//div[contains(@class,'css-2b097c-container')]").send_keys(Keys.TAB,"Bitcot",Keys.ARROW_UP,Keys.ARROW_DOWN,Keys.ENTER)
time.sleep(5)
driver.find_element_by_xpath("//label[contains(text(),'Quotes')]").click()
driver.find_element_by_xpath("//label[contains(text(),'Tickets')]").click()
driver.find_element_by_xpath("//label[contains(text(),'Inspections')]").click()
driver.find_element_by_xpath("//label[contains(text(),'PegAssure')]").click()
driver.find_element_by_xpath("//button[@class='btn cst_btn btn_danger mr-2']").click()
